 export default {
  name: 'default',
  type: 'mysql',
  host: 'db',
  port: 3306,
  username: process.env.MYSQL_USERNAME,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
  synchronize: false,
  logging: true,
  entities: ['../../src/**/*.entity.{js,ts}'],
  migrations: ['../../src/migrations/*.{js,ts}'],
  seeds: ['../../src/migrations/seeders/*.seed.{js,ts}'],
  factories: ['../../src/migrations/factories/*.factory.{js,ts}'],
  cli: {
    migrationsDir: '../../src/migrations',
    entitiesDir: '../../src/entities',
    seedersDir: '../../src/migrations/seeds',
    factoriesDir: '../../src/migrations/factories',
  },
}